---
- name: Build BIGIP configuration
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Generate AS3 folders
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ backup_dir }}"
        - "{{ backup_dir }}/json"
        - "{{ backup_dir }}/yaml"
      run_once: yes

    - name: generate AS3
      import_role:
        name: bigip_as3_gen
