APP-forward-net:
  type: forward
  forwardType: ip
  name: VS-forward-net
  port: 0
  snat: none
  l4: tcp
  vips:
    - ip: 10.0.0.0/8
      source: 10.30.30.0/28
  profile:
    l4:
      name: /Common/Shared/FL4-forward
      location: common
  vlans:
    - /Common/vlan2